name: "Build Kiota"
runs:
  using: "composite" # <-- this is the important part
  steps:
    - uses: actions/checkout@v4
      with:
        repository: microsoft/kiota
        ref: main
        path: kiota
    - name: Build
      run: dotnet publish --nologo kiota/src/kiota/kiota.csproj -c Release -p:PublishSingleFile=true -r linux-x64 --output bin
      shell: bash
    - name: Build
      run: ls -la bin
      shell: bash
