name: "Create version"
description: "Create version"
outputs:
  enhancedVersion:
    description: "Enhanced version"
    value: ${{ steps.version.outputs.enhancedVersion }}
runs:
  using: "composite"
  steps:
    - name: Create version
      run: |
        ENHANCED_VERSION="${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}"
        if [[ "${{ steps.gitversion.outputs.Patch }}" -ne '' ]]; then ENHANCED_VERSION="${ENHANCED_VERSION}.${{ steps.gitversion.outputs.Patch }}"; fi
        if [[ -f "src/Apple.AppStoreConnect/api-version.txt" ]]; then ENHANCED_VERSION="${ENHANCED_VERSION}.$(sed '2q;d' src/Apple.AppStoreConnect/api-version.txt)"; fi
        if [[ "${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}" -ne '' ]]; then ENHANCED_VERSION="${ENHANCED_VERSION}-${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}"; fi
        echo "enhancedVersion=${ENHANCED_VERSION}" >> "$GITHUB_OUTPUT"
      id: version
      shell: bash
