name: "Create version"
description: "Create version"
outputs:
  enhancedVersion:
    description: "Enhanced version"
    value: ${{ steps.version.outputs.enhancedVersion }}
runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.5'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.1.1
    - run: |
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
      shell: bash
    - name: Create version
      run: |
        ENHANCED_VERSION="${{ steps.gitversion.outputs.MajorMinorPatch }}"
        if [[ -f "src/Apple.AppStoreConnect/api-version.txt" ]]; then ENHANCED_VERSION="${ENHANCED_VERSION}.$(sed '2q;d' src/Apple.AppStoreConnect/api-version.txt)"; fi
        if [[ "${{ steps.gitversion.outputs.PreReleaseTag }}" != '' ]]; then ENHANCED_VERSION="${ENHANCED_VERSION}-${{ steps.gitversion.outputs.PreReleaseTag }}"; fi
        echo "enhancedVersion=${ENHANCED_VERSION}" >> "$GITHUB_OUTPUT"
      id: version
      shell: bash
