name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - uses: actions/checkout@v4
      - name: Tool restore
        run: dotnet tool restore
      - uses: ./.github/actions/build-kiota
        id: kiota
      - name: Restore
        run: dotnet restore --nologo
        env:
          KIOTA_BIN: ${{ steps.kiota.outputs.command }}
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release
      - name: Test
        run: dotnet test --nologo --no-build --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .Net 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - uses: ./.github/actions/build-kiota
        id: kiota
      - name: Restore
        run: dotnet restore --nologo
        env:
          KIOTA_BIN: ${{ steps.kiota.outputs.command }}
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag --exclude Client
